### ISSUE TITLE
MaterialModule

### ISSUE THREAD

**Issue by tiedyejedi** [bsubedi26/ng2-ShoppingCart#5]
ERROR in C:/Web/myCart/src/app/app.module.ts (5,10): Module '"C:/Web/myCart/node_modules/@angular/material/material"' has no exported member 'MaterialModule'.

ERROR in MaterialModule is not an NgModule

ERROR in C:/Web/myCart/src/app/app.module.ts (5,10): Module '"C:/Web/myCart/node_modules/@angular/material/material"' has no exported member 'MaterialModule'.
webpack: Failed to compile.

brand new install of Angular CLI and Material

**Comment by bsubedi26** [comment]
If you cloned this repo directly and npm install the dependencies, everything should work. Try deleting your node_modules folder and running `npm install` again.  If you're copying parts of this repos code to your own projects, then there maybe issues with angular material versions. This repos angular material is not the latest so that maybe an issue.

**Comment by melalitesh** [comment]
Facind the same issue on my Mac machine with Nodev version v6.11.0

**Comment by bsubedi26** [comment]
This issue should be fixed with this commit (https://github.com/bsubedi26/ng2-ShoppingCart/commit/36e4c22e27c0f4d8912b2c2541f83ae27a22d8ee). Pull the latest changes from master and everything should work and if something does not work reply back on here.
